katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = "katalog"

urlpatterns = [
    path("", show_katalog, name = "show_katalog"),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path("katalog/", include("katalog.urls")),
    path("mywatchlist/", include("mywatchlist.urls")),
    path("todolist/", include("todolist.urls")),

]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist
 #sesuaikan dengan nama fungsi yang dibuat
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import create_task
from todolist.views import hapus
from todolist.views import cek_selesai
from todolist.views import todolist_json

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='createtask'),
    path('hapus/<int:id>', hapus, name='hapus'),
    path('cek-selesai/<int:id>', cek_selesai, name='cek-selesai'),
    path('json/', todolist_json, name='todolist_json'),
]

todolist/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

class ToDoListItem(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    date = models.DateField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms

from todolist.models import ToDoListItem

class TaskForm(forms.ModelForm):
    class Meta:
        model = ToDoListItem
        fields = {"title", "description"}

todolist/views.py
from urllib import response
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.core import serializers

from django.shortcuts import render
from todolist.forms import TaskForm
from todolist.models import ToDoListItem

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse



# Create your views here.

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    user = request.user
    data_todolist = ToDoListItem.objects.filter(user = user)
    context = {
    'list_todolist': data_todolist,
    'nama': 'Vero',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        form.instance.user = request.user
        form.instance.date = datetime.datetime.now()
        if form.is_valid():
            form.save()
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            return response
    else:
        form = TaskForm()
    return render(request, "createtask.html", {'form': form})

def hapus(request, id):
    task = ToDoListItem.objects.get(id=id)
    task.delete()
    return show_todolist(request)

def cek_selesai(request, id):
    task = ToDoListItem.objects.get(id=id)
    if task.is_finished:
        task.is_finished = False
    else:
        task.is_finished = True
    task.save()
    return show_todolist(request)


@login_required(login_url='/todolist/login/')
def todolist_json(request):
    task = ToDoListItem.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", task), content_type="application/json")

    

todolist/templates/createtask.html
{% extends 'base.html' %}

{% block meta %}
<title>Create Task</title>
{% endblock meta %}

{% block content %}


<style>

    h1{
        text-align: center;
        vertical-align: middle;   
        box-sizing: border-box;
    }
    
    table{
        text-align: left;
    }
    body {
        align-items: center;
        background-color: #000;
        display: flex;
        justify-content: center;
        height: 100vh;
        text-align: center;
        vertical-align: middle;
        color: #000;
      }
    
    
      .container{
      max-width: 550px;
      padding: 15px;
      margin: 170px;
      color: rgb(255, 255, 255);
      vertical-align: middle;
    }
    
    
    .wrapper{
      width: 100%;
      background: rgba(209, 10, 76, 0.642);
      border-radius: 10px;
      box-shadow: 0px 4px 10px 1px rgba(210, 17, 184, 0.1);
      padding: 15px;
      vertical-align: middle;
      
    }
    
    .submit {
      background-color: rgba(221, 0, 85, 0.547);
      border-radius: 3px;
      box-sizing: border-box;
      color: rgb(255, 255, 255);
      cursor: pointer;
      font-size: 22px;
      height: 50px;
      margin-top: 20px;
      outline: 0;
      text-align: center;
      width: 100%;
      vertical-align: middle;
    }
    
    td{
        color: rgb(255, 255, 255);
        text-align: center;
    }
    h1{
        color: #000;
    }
    
    .submit:hover {
      box-shadow: 0 0.5em 0.3em -0.2em var(--hover);
      transform: translateY(-0.15em);
    }
    
    </style>
<body  style="background-image: url(https://www.wallpaperuse.com/wallp/26-264578_m.jpg);">
<div class="container">
    <div class="wrapper">
        <h1>Create Task</h1>

    <form method="POST" >  
        {% csrf_token %}  
        <table>  
            <tr>
                <td>Title: </td>
                <td>{{form.title}}</td>
            </tr>
                    
            <tr>
                <td>Description: </td>
                <td>{{form.description}}</td>
            </tr>
            <tr>  
                <td></td>
                <td><button type="submit" class="submit" value="POST">Create Task</button></td>  
            </tr>  
        </table>  
    </form>

{% if messages %}  
    <ul>   
        {% for message in messages %}  
            <li>{{ message }}</li>  
            {% endfor %}  
    </ul>   
{% endif %}



{% endblock content %}
</body>


<!-- https://getbootstrap.com/docs/4.3/components/card/ -->
<!-- https://mdbootstrap.com/docs/standard/content-styles/hover-effects/ -->

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}


<style>

h1 {
    text-align: center;
    
}
.center {
    display: flex;
    justify-content: center;
    align-items: center;
}

body {
    align-items: center;
    text-align: center;
    vertical-align: middle;
    justify-content: center;
    display: flex;
    height: 80vh;
}

.container {
  max-width: 500px;
  padding: 0 20px;
  margin: 170px auto;
  color: aliceblue;
}


.wrapper {
  width: 100%;
  background: rgba(209, 10, 76, 0.531);
  border-radius: 5px;
  box-shadow: 0px 4px 10px 1px rgba(210, 17, 184, 0.1);
  padding: 10px;
  
}

.wrapper:hover {
  transform: translateY(-0.15em);
}

.submit {
  background-color: rgb(221, 0, 85);
  border-radius: 3px;
  box-sizing: border-box;
  color: rgb(0, 0, 0);
  cursor: pointer;
  font-size: 22px;
  height: 50px;
  margin-top: 20px;
  text-align: center;
  width: 100%;
}

.submit:hover {
  transform: translateY(-0.15em);
}

table, th, td {
    justify-content: center; 
    text-align: center; 
    border: 1px 
    solid rgb(255, 255, 255);
    margin-bottom: 20px;
    margin-top: 20px;
}
tr { text-align: center;background-color: rgba(245, 2, 2, 0.522);}
</style>
<body  style="background-image: url(https://www.wallpaperuse.com/wallp/26-264578_m.jpg);">
<div class="center">
<div class = "login">
    <div class="container">
        <div class="wrapper">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
            <tr>
                <td>Username</td>
                <td><input type="text" name="username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password</td>
                <td><input type="password" name="password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><button type="text" class="submit" value="Login">Login</button>

                </td>
            </tr>
    </form>

    {% if messages %}
        <th>
            {% for message in messages %}
                <th>{{ message }}</th>
            {% endfor %}
        <th>
    {% endif %}     
        
    <p>Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>
        <p>
</div>
</body>

{% endblock content %}


<!-- https://getbootstrap.com/docs/4.3/components/card/ -->
<!-- https://mdbootstrap.com/docs/standard/content-styles/hover-effects/ -->

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}
<style>

h1 {
    text-align: center;
    vertical-align: middle;   
    box-sizing: border-box;
}

table {
    text-align: left;
}

body {
    align-items: center;
    text-align: center;
    vertical-align: middle;
    justify-content: center;
    display: flex;
    height: 100vh;
  }


.container {
  max-width: 700px;
  padding: 0 20px;
  margin: 170px auto;
  color: aliceblue;
  vertical-align: middle;
}


.wrapper {
  width: 100%;
  background: rgba(209, 10, 76, 0.642);
  border-radius: 50px;
  box-shadow: 0px 4px 10px 1px rgba(210, 17, 184, 0.1);
  padding: 15px;
  vertical-align: middle;
}

.submit {
  background-color: rgba(221, 0, 85, 0.547);
  border-radius: 75px;
  box-sizing: border-box;
  color: rgb(0, 0, 0);
  cursor: pointer;
  font-size: 22px;
  height: 50px;
  margin-top: 20px;
  margin-bottom: 10px;
  text-align: center;
  width: 100%;
  vertical-align: middle;

}

.submit:hover {
  transform: translateY(-0.15em);
}

td {
    color: aliceblue;
}


</style>
<body style="background-image: url(https://www.wallpaperuse.com/wallp/26-264578_m.jpg);">


    <div class="container">
        <div class="wrapper">
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td>
                        
                        <button type="submit" class="submit" value="Daftar">Submit</button>
                    
                    </td>  
                </tr>  
            </table>
        </form>

</div>  
</body>
{% endblock content %}


<!-- https://getbootstrap.com/docs/4.3/components/card/ -->
<!-- https://mdbootstrap.com/docs/standard/content-styles/hover-effects/ -->

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

<style>

.wrapper {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  row-gap: 3px;
  column-gap: 3px;
}

a {
  color: black;
}

.card {
    justify-content: center;
    color: rgb(255, 255, 255);
    background-color: rgba(165, 37, 86, 0.666);
}

.card-body {
    justify-content: center;
    text-align: center;
    background-color: rgba(249, 0, 108, 0.322);
    opacity: 0,5;
}

.card-text {
  margin-top: 20px;
  margin-bottom: 10px;
}

.card-font {
  color: black;

}
.card:hover {
  transform: translateY(-10px);
}

h1{
  font-size: 20px;
}
h2{
  color: aliceblue;
  font-size: 18px;
}

h3{
  justify-content: center;
  text-align: center;
  font-size: 15px;
  color: aliceblue;
  margin-bottom: 5px;
}

h4 {
  font-size: 30px;
}

h5 {
  justify-content: center;
  text-align: center;
  color: rgb(255, 255, 255);
  font-size: 25px;
  margin-left: auto;
  margin-right: auto;
  margin-top: 7px;
  margin-bottom: 7px;
}

h6 {
  font-size: 15px;
  margin-top: 7px;
  margin-bottom: 7px;
}

.submit {
      background-color: rgba(165, 37, 86, 0.819);
      border-radius: 80px;
      max-width: fit-content;
      min-width: fit-content;
      vertical-align: middle;
      box-sizing: content-box;
      color: rgb(252, 252, 252);
      cursor: pointer;
      font-size: 15px;
      height: 25px;
      margin-top: 20px;
      outline: 0;
      text-align: center;
      width: 50%;
      margin-left: 10px;
      margin-right: 10px;
    }

  .submit:hover {
    box-shadow: 0 0.5em 0.3em -0.2em var(--hover);
    transform: translateY(-0.15em);
}


</style>

<h2>User in session : {{user}} </h2>
<h5>{{user}}'s List of Tasks </h5>
<h3><button type="button" class="submit" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Create a new task</button></h3>
<body style="background-image: url(https://www.wallpaperuse.com/wallp/26-264578_m.jpg);">
  

    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    <div class="wrapper">

</div>
</div>


<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Fill out your task title and description</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="card-body">
          <form class="create_task" method="POST">
              {% csrf_token %}
              <div class="card-body" style="padding-left:0.5%;margin-top: 5px; margin-bottom: 5px;">
              <h3><input 
                type="text" 
                class="form-control" 
                id="floatingInput" 
                name="title" ></h3>
                <label for="floatingInput">Title</label>
              </div>
            
              <div class="card-body" style="padding-left:0.5%;margin-top: 5px;margin-bottom: 5px;">
              <h3><textarea 
                class="form-control" 
                id="floatingDescription" 
                name="description" rows="4" cols="50"></textarea></h3>
                <label for="floatingDescription" style="padding-left:2.5%;">Description</label>
              </div>
            </form>
      </div>
      <div class="card-body">
        <h3><button type="button" class="submit" data-bs-dismiss="modal">Close</button> 
        <button type="button" class="submit" onclick="create()">Create Task</button></h3>
      </div>
    </div>
  </div>
</div>  

<h3><button class ="submit"><a href="{% url 'todolist:logout' %}" style="color:aliceblue ;">Logout</a></button></h3>
<h3>Sesi terakhir login : {{last_login}}</h3>


</body>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>

    $(document).ready(() => {
        get_task();
    })
    function create() {
        const form = $(".create_task");
        $.ajax({
            type: "POST",
            url: "/todolist/create-task/",
            data: form.serialize(),
        }).done(function (data) {
            form.trigger("reset");
            get_task();
        });
        $("#staticBackdrop").modal("hide");
    }

    function delete_task(id) {
        $.ajax({
            type: "GET",
            url: "/todolist/hapus/" + id,
            data: {csrfmiddlewaretoken: '{{ csrf_token }}'}
        }).done((data) => {
            get_task();
        })
    }

    function change_status(id) {
        $.ajax({
            type: "GET",
            url: "/todolist/cek-selesai/" + id,
            data: {csrfmiddlewaretoken: '{{ csrf_token }}', pk: id}
        }).done((data) => {
            get_task();
        })
    }

    function get_task() {
        $.ajax({
            type: "GET",
            url: "/todolist/json/"
        }).done((data) => {
            putTaskList(data);
        });
    }

    function putTaskList(data) {
        const displayTable = $('.wrapper');
        displayTable.empty();
        data.forEach(task => {
            const taskCard = `
            <div class="card" style="width: 18rem; margin-right: auto; margin-left: auto; padding-bottom: 20; margin-top: 20px;">
            <div class="card-body">
            <h4 class="card-font">${task.fields.title}</h4>
            <h6 class="card-text">${task.fields.date}</h6>
            <p class="card-font">${task.fields.description}</p>
            ${task.fields.is_finished ? "Selesai" : "Belum Selesai"} <br>
              <input type="submit" value="Change Status" class="submit" onclick="change_status(${task.pk})" />
              <input type="submit" value="Delete Task"  class="submit" onclick="delete_task(${task.pk})" />
        </div>
      </div>`
      ;
            displayTable.append(taskCard);
        })
    };
    
</script>

{% endblock content %}

<!-- https://getbootstrap.com/docs/4.3/components/card/ -->
<!-- https://mdbootstrap.com/docs/standard/content-styles/hover-effects/ -->
<!-- https://getbootstrap.com/docs/4.0/components/modal/ -->